eegnet:
  F1: 16
  D: 2
  F2: 4
  dropout_rate: 0.5
  bottleneck_dim: 0
  kernel_length: 64
  temporal_type: 'vanilla'
  activation: 'hard_swish'  # resolve in Python
  l2_weight: 0.0
  norm_layer: 'BATCH'

model_input_lookup:
  x: data
  attention_mask: attention_mask