head:
  type: flat
  num_classes: 2
  l2_weight: 0.0

loss:
  _target_: ml_tflm.training.loss.BinaryLoss

evaluator:
  _target_: ml_tflm.training.metrics.metric_evaluator
  label_config: null
  prediction_caster: cast_prediction_binary

model_target_lookup:
  targets: labels
  entropy_targets: internal_label