head:
  type: hierarchical

loss:
  _target_: ml_tflm.training.loss.HierarchicalLoss

evaluator:
  _target_: ml_tflm.training.metrics.metric_evaluator
  label_config: null
  prediction_caster: cast_prediction_hierarchical

model_target_lookup:
  targets: labels
  label_mask: label_mask