name: snakemake_env  
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python version
  - python=3.11  # Ensure compatibility with Snakemake & ML frameworks

  # Workflow Management
  - snakemake  # For reproducible data pipelines
  - dvc  # Data Version Control for tracking datasets
  - git  # Version control
