project_name: AGENDA
site_name: South Africa
dataset_name: EEG
dataset_path: ${oc.env:DATA}/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/processed_dataset.h5

cv_datasets:
  cv_dataset_folds_dir: ${oc.env:DATA}/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/dataset_splits
  fold_index: 0
  k_folds: 5

final_test_set:
  final_eval: false
  test_dataset_dir: ${oc.env:DATA}/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/dataset_splits
  testset_file_name: test_split.json