defaults: 
  - losses: hierarchical_loss
  - early_stopping: default

training:
  batch_size: 4
  epochs: 100
  learning_rate: 0.001
  optimizer: "Adam"
  resume: false
  checkpoint_path: null    # Optional path to load from; will default to latest in output_dir