_target_: "ml.models.classifier.multihead.MultiHeadClassifier"
type: multihead   # Multi-head classifier with 3 levels
params:
  num_classes: [2, 2, 2]  # Number of classes for each level
  hidden_dim: 128         # Hidden dimension for classifiers
