defaults:
  - dataset: sample_refiltered
  - optimizer: adam
  - training: default
  - component/feature_extractor: EEGNet
  - component/pooling_layer: AveragePooling
  - component/classifier_head: Binary
  - _self_

hydra:
  run:
    dir: .
