defaults:
  - architecture: flat_mod1
  - dataset: minimal
  - optimizer: adam
  - training: default
  - component/feature_extractor: EEGNet_mod1
  - component/pooling_layer: attention_pooling
  - _self_

hydra:
  run:
    dir: .
