defaults:
  - dataset: sample_balanced
  - optimizer: adam
  - training: default
  - component/feature_extractor: EEGNet
  - component/pooling_layer: GRUPooling
  - component/classifier_head: Binary
  - _self_

hydra:
  run:
    dir: .
