defaults:
  - dataset: sample01
  - optimizer: adam
  - training: default
  - component/feature_extractor: EEGNet
  - component/pooling_layer: SingleAttentionPooling
  - component/classifier_head: Flat
  - _self_

hydra:
  run:
    dir: .
