experiments:
  electrode_ablation:
    sites_to_include: 
      - south_africa
    montages_to_process:
      monopolar:
        - standard_10_20
        #- 10_20_no_A1_A2
        #- 10_20_no_T3_T4
        #- 10_20_no_A1_A2_Cz
