montages:
  monopolar:
    standard_10_20:
      channels: ['A1', 'FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Cz', 'Pz', 'A2']
    10_20_no_A1_A2:
      channels: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Cz', 'Pz']
    10_20_no_T3_T4:
      channels: ['A1', 'FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T5', 'T6', 'Fz', 'Cz', 'Pz', 'A2']
    10_20_no_A1_A2_Cz:
      channels: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Pz']
      
  bipolar:
    19_channel:
      anodes:
        - ['', 'FP1', 'FP1', 'FP2', 'FP2', '']
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['A1', 'T3', 'C3', 'CZ', 'C4', 'T4']
        - ['', 'T3', 'C3', 'C4', 'T4', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
      cathodes:
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'T3', 'C3', 'C4', 'T4', '']
        - ['T3', 'C3', 'CZ', 'C4', 'T4', 'A2']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
        - ['', 'O1', 'O1', 'O2', 'O2', '']
    17_channel_no_A1_A2:
      anodes:
        - ['', 'FP1', 'FP1', 'FP2', 'FP2', '']
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'T3', 'C3', 'CZ', 'C4', '']
        - ['', 'T3', 'C3', 'C4', 'T4', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
      cathodes:
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'T3', 'C3', 'C4', 'T4', '']
        - ['', 'C3', 'CZ', 'C4', 'T4', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
        - ['', 'O1', 'O1', 'O2', 'O2', '']
    17_channel_no_T3_T4:
      anodes:
        - ['', 'FP1', 'FP1', 'FP2', 'FP2', '']
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'A1', 'C3', 'CZ', 'C4', '']
        - ['', 'A1', 'C3', 'C4', 'A2', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
      cathodes:
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'A1', 'C3', 'C4', 'A2', '']
        - ['', 'C3', 'CZ', 'C4', 'A2', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
        - ['', 'O1', 'O1', 'O2', 'O2', '']
    16_channel:
      anodes:
        - ['', 'FP1', 'FP1', 'FP2', 'FP2', '']
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'T3', '', '', 'C4', '']
        - ['', 'T3', 'C3', 'C4', 'T4', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
      cathodes:
        - ['', 'F7', 'F3', 'F4', 'F8', '']
        - ['', 'T3', 'C3', 'C4', 'T4', '']
        - ['', 'C3', '', '', 'T4', '']
        - ['', 'T5', 'P3', 'P4', 'T6', '']
        - ['', 'O1', 'O1', 'O2', 'O2', '']
  
