# config/dataset/agenda/south_africa.yaml
project_name: AGENDA
site_name: South Africa
dataset_name: EEG
#dataset_path: /data/ndcn-cortico-basal-ganglia-model/ndcn1133/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/processed_dataset.h5
dataset_path: ${env:DATA}/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/processed_dataset.h5
#output_dir: ${env:DATA}/AGENDA-Headset-Algorithm/outputs/${experiment_name}/${run_id}

cv_datasets:
  cv_dataset_folds_dir: /data/ndcn-cortico-basal-ganglia-model/ndcn1133/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/dataset_splits
  fold_index: 0
  k_folds: 5

final_test_set:
  final_eval: False
  test_dataset_dir: /data/ndcn-cortico-basal-ganglia-model/ndcn1133/AGENDA-Headset-Algorithm/data/experiment_datasets/electrode_ablation/south_africa/monopolar/standard_10_20/dataset_splits
  testset_file_name: test_split.json
  