model:
  _target_: ml_tflm.models_tf.classifiers.EEGNetHierarchicalClassifier
  eegnet_args: ${component.feature_extractor}
  pooling_args: ${component.pooling_layer}

loss:
  _target_: ml_tflm.training.loss.HierarchicalLoss

evaluator:
  _target_: ml_tflm.training.metrics.metric_evaluator
  label_config: null
  prediction_caster: cast_prediction_hierarchical

model_input_lookup:
  x: data
  attention_mask: attention_mask

model_target_lookup:
  targets: labels
  label_mask: label_mask