pool:
  scorer: MLP
  hidden_dim: 16
  activation: tanh  # resolve in Python
  num_heads: 2

loss:
  _target_: ml_tflm.training.loss.ConditionalEntropyLoss

  label_to_heads: {3: [0], 4: [1], 5: [1]}
  lambda_entropy: 0.01