pool:
  scorer: MLP
  hidden_dim: 16
  activation: tanh  # resolve in Python
  num_heads: 1

loss:
  _target_: ml_tflm.training.loss.ConditionalEntropyLoss

  label_to_heads: {3: [0], 4: [0], 5: [0]}
  lambda_entropy: 0.0