pool:
  scorer: TCNGated
  tcn_hidden: 16
  mlp_dim: 16
  num_layers: 5
  num_heads: 1

loss:
  _target_: ml_tflm.training.loss.ConditionalEntropyLoss

  label_to_heads: {3: [0], 4: [0], 5: [0]}
  lambda_entropy: 0.02