use_h5: True

val_frac: 0.2
test_frac: 0.0
k_fold: False

train_path: "ml_tflm/dataset/agenda_data_01/train.tfrecord"
val_path: "ml_tflm/dataset/agenda_data_01/val.tfrecord"
meta_path: "ml_tflm/dataset/agenda_data_01/meta.json"

batch_sz: 1

attention_warmup_epoch: 0

epochs: 20
steps_per_epoch: 240

anneal_interval: 0
anneal_coeff: 0.5

save_ckpt: True
ckpt_interval: 5
ckpt_save_dir: "ml_tflm/training/checkpoints"

load_ckpt: False
ckpt_load_dir: "ml_tflm/training/checkpoints"

metric_save_dir: "ml_tflm/training/results/train_metrics.json"