val_frac: 0.2
test_frac: 0.15
k_fold: False
stratify: True
internal_label_cap_keys: [0,3,4,5]
# internal_label_cap_values: [240,120,60,60]
internal_label_cap_values: [450, 260, 94, 96]
class_balance: True

mirror_flag: False

batch_sz: 32
chunk_size: 256

epochs: 20
steps_per_epoch: 100

attention_warmup_epoch: 0

anneal_interval: 0
anneal_coeff: 0.4

save_ckpt: True
ckpt_interval: 5
ckpt_save_dir: "ml_tflm/training/checkpoints"

load_ckpt: False
ckpt_load_dir: "ml_tflm/training/checkpoints"

metric_save_dir: "ml_tflm/training/results/train_metrics.json"