val_frac: 0.2
test_frac: 0.0
k_fold: False

mirror_flag: False

batch_sz: 1

epochs: 20
steps_per_epoch: 240

attention_warmup_epoch: 0

anneal_interval: 0
anneal_coeff: 0.4

save_ckpt: True
ckpt_interval: 5
ckpt_save_dir: "ml_tflm/training/checkpoints"

load_ckpt: False
ckpt_load_dir: "ml_tflm/training/checkpoints"

metric_save_dir: "ml_tflm/training/results/train_metrics.json"