val_frac: 0.3
test_frac: 0.0
k_fold: False

epochs: 40
steps_per_epoch: 10

save_ckpt: True
ckpt_interval: 5
ckpt_save_dir: "ml_tflm/training/checkpoints"

load_ckpt: False
ckpt_load_dir: "ml_tflm/training/checkpoints"